# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = [""]
description = "minimal example of @google-cloud/storage compatibility issue"
language = "javascript"
manifest_version = 2
name = "fastly-gcs"
service_id = ""

[scripts]
  build = "npm exec webpack && npm exec js-compute-runtime ./bin/index.js ./bin/main.wasm"
